name: Show input

description: show input

inputs:
  args:
    description: arg
    required: true
  default-check:
    description: default check
    required: false
    type: string
    default: test-default


runs:
  using: composite
  steps:
    - name: echo
      shell: bash
      run: |
        echo ${{ inputs.args }}

    - name: echo default
      shell: bash
      run: |
        echo ${{ inputs.default-check }}