name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: "Version number to bump"
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install `cargo-get`
        run: cargo install cargo-get

      - name: Set Crate Version as Environment Variable
        id: set_crate_version
        run: |
          CARGO_TOML_VERSION=$(cargo get package.version)
          echo "version=$CARGO_TOML_VERSION" >> $GITHUB_OUTPUT

      - name: build
        shell: bash
        run: cargo build --release

      - name: create zip
        shell: bash
        run: zip -j actions-lab.zip target/release/actions-lab

      - name: Create Release
        uses: actions/github-script@v5
        id: release
        with:
          script: |
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "v${{ steps.set_crate_version.outputs.version }}",
              generate_release_notes: true
            });
            return release.id;
          result-encoding: string

      - name: Upload a release asset
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises;
            const asset = await fs.readFile("./actions-lab.zip");
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.release.outputs.result }},
              name: "ubuntu-latest.zip",
              data: asset,
              headers: {
                "content-type": "application/zip",
                "content-length": asset.length
              }
            });

  bump-version:
    name: Bump Version
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install `cargo-edit`
        run: cargo install cargo-edit

      - name: Install `cargo-get`
        run: cargo install cargo-get

      - id: cargo-set-version
        name: Set Version
        run: cargo set-version --bump ${{ inputs.version }}

      - name: Set Crate Version as Environment Variable
        id: set_crate_version
        run: |
          CARGO_TOML_VERSION=$(cargo get package.version)
          echo "version=$CARGO_TOML_VERSION" >> $GITHUB_OUTPUT

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: bump version to v${{ steps.set_crate_version.outputs.version }}"
          branch: "chore/bump-version-to-v${{ steps.set_crate_version.outputs.version }}"
          delete-branch: true
          title: "chore: bump version to v${{ steps.set_crate_version.outputs.version }}"
          body: |
            Bumps the version to v${{ steps.set_crate_version.outputs.version }}.

            This PR was created by the [release workflow](${{ github.event.repository.html_url }}/actions/workflows/release.yml).

            [release workflow]: ${{ github.event.repository.html_url }}/actions/workflows/release.yml
