name: set output check

on: workflow_dispatch

jobs:
  output-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: output1
        id: out1
        run: echo ::set-output name=out::test1,test2

      - name: echo1
        run: echo ${{ steps.out1.outputs.out }}

      - name: output2
        id: out2
        run: echo ::set-output name=out::["test1", "test2"]

      - name: echo1
        run: echo ${{ steps.out2.outputs.out }}

      - name: if check
        run: |
          if [ ${{ true }} -eq true ]; then
            echo success
          else
            echo failed
          fi

      - name: if check2
        run: |
          if [ ${{ true }} ]; then
            echo success
          else
            echo failed
          fi

      - name: csv check
        uses: ./.github/actions/echo
        with:
          args: test1, test2

      - name: dispatch test
        uses: peter-evans/repository-dispatch@v1
        repository: rabe1028/actions-lab
        token: ${{ secrets.GITHUB_TOKEN }}
        client-pyaload: ''

      # 改行込みで埋め込まれるため、ここだとecho test1の次に、test2というscriptを呼び出そうとして落ちる
      # - name: list check
      #   uses: ./.github/actions/echo
      #   with:
      #     args: |
      #       test1
      #       test2
